import type { EditorLabels } from './types'

export const wujieeZhCNLabels: EditorLabels = {
  heading: '标题',
  bold: '粗体',
  italic: '斜体',
  strike: '删除线',
  quote: '引用',
  unorderedList: '无序列表',
  orderedList: '有序列表',
  taskList: '任务列表',
  inlineCode: '行内代码',
  codeBlock: '代码块',
  link: '链接',
  image: '图片',
  table: '表格',
  uploadImage: '上传图片',
  uploadingImage: '图片上传中…',
  horizontalRule: '分割线',
  edit: '编辑',
  split: '分栏',
  preview: '预览',
  fullscreen: '全屏',
  exitFullscreen: '退出全屏',
  characters: '个字符',
  emptyPreview: '暂无可预览内容',
  linkText: '链接文字',
  imageAlt: '图片说明',
  linkAddress: '请输入链接地址',
  linkTextLabel: '链接文字',
  confirm: '插入链接',
  cancel: '取消',
  invalidLink: '请输入有效的 HTTP、HTTPS、邮箱、电话或站内链接',
  addRow: '增加行',
  addColumn: '增加列',
  deleteRow: '删除行',
  deleteColumn: '删除列'
}

export const wujieeEnUSLabels: EditorLabels = {
  heading: 'Heading',
  bold: 'Bold',
  italic: 'Italic',
  strike: 'Strikethrough',
  quote: 'Quote',
  unorderedList: 'Bulleted list',
  orderedList: 'Numbered list',
  taskList: 'Task list',
  inlineCode: 'Inline code',
  codeBlock: 'Code block',
  link: 'Link',
  image: 'Image',
  table: 'Table',
  uploadImage: 'Upload image',
  uploadingImage: 'Uploading image…',
  horizontalRule: 'Horizontal rule',
  edit: 'Edit',
  split: 'Split',
  preview: 'Preview',
  fullscreen: 'Fullscreen',
  exitFullscreen: 'Exit fullscreen',
  characters: 'characters',
  emptyPreview: 'Nothing to preview',
  linkText: 'link text',
  imageAlt: 'image description',
  linkAddress: 'Enter link URL',
  linkTextLabel: 'Link text',
  confirm: 'Insert link',
  cancel: 'Cancel',
  invalidLink: 'Enter a valid HTTP, HTTPS, email, phone, or relative URL',
  addRow: 'Add row',
  addColumn: 'Add column',
  deleteRow: 'Delete row',
  deleteColumn: 'Delete column'
}

export const zhCNLabels = wujieeZhCNLabels
export const enUSLabels = wujieeEnUSLabels
